baseapp_ = 'sgapapp_'
DELETE_ = 'delete_'
CREATE_ = 'create_'
UPDATE_ = 'update_'
LIST_ = 'list_'
DETAIL_ = 'detail_'


#Bairro
BAIRRO = 'bairro'
BAIRRO_DELETE = baseapp_+DELETE_+BAIRRO
BAIRRO_CREATE = baseapp_+CREATE_+BAIRRO
BAIRRO_UPDATE = baseapp_+UPDATE_+BAIRRO
BAIRRO_LIST = baseapp_+LIST_+BAIRRO
BAIRRO_DETAIL = baseapp_+DETAIL_+BAIRRO

#Chamado
CHAMADO = 'chamado'
CHAMADO_DELETE = baseapp_+DELETE_+CHAMADO
CHAMADO_CREATE = baseapp_+CREATE_+CHAMADO
CHAMADO_UPDATE = baseapp_+UPDATE_+CHAMADO
CHAMADO_LIST = baseapp_+LIST_+CHAMADO
CHAMADO_DETAIL = baseapp_+DETAIL_+CHAMADO

#Dashboard
DASHBOARD = 'dashboard'
DASHBOARD_DELETE = baseapp_+DELETE_+DASHBOARD
DASHBOARD_CREATE = baseapp_+CREATE_+DASHBOARD
DASHBOARD_UPDATE = baseapp_+UPDATE_+DASHBOARD
DASHBOARD_LIST = baseapp_+LIST_+DASHBOARD
DASHBOARD_DETAIL = baseapp_+DETAIL_+DASHBOARD

#Email
EMAIL = 'email'
EMAIL_DELETE = baseapp_+DELETE_+EMAIL
EMAIL_CREATE = baseapp_+CREATE_+EMAIL
EMAIL_UPDATE = baseapp_+UPDATE_+EMAIL
EMAIL_LIST = baseapp_+LIST_+EMAIL
EMAIL_DETAIL = baseapp_+DETAIL_+EMAIL


#Endereco
ENDERECO = 'endereco'
ENDERECO_DELETE = baseapp_+DELETE_+ENDERECO
ENDERECO_CREATE = baseapp_+CREATE_+ENDERECO
ENDERECO_UPDATE = baseapp_+UPDATE_+ENDERECO
ENDERECO_LIST = baseapp_+LIST_+ENDERECO
ENDERECO_DETAIL = baseapp_+DETAIL_+ENDERECO



#equipamento
EQUIPAMENTO = 'equipamento'
EQUIPAMENTO_DELETE = baseapp_+DELETE_+EQUIPAMENTO
EQUIPAMENTO_CREATE = baseapp_+CREATE_+EQUIPAMENTO
EQUIPAMENTO_UPDATE = baseapp_+UPDATE_+EQUIPAMENTO
EQUIPAMENTO_LIST = baseapp_+LIST_+EQUIPAMENTO
EQUIPAMENTO_DETAIL = baseapp_+DETAIL_+EQUIPAMENTO



#grafico
GRAFICO = 'grafico'
GRAFICO_DELETE = baseapp_+DELETE_+GRAFICO
GRAFICO_CREATE = baseapp_+CREATE_+GRAFICO
GRAFICO_UPDATE = baseapp_+UPDATE_+GRAFICO
GRAFICO_LIST = baseapp_+LIST_+GRAFICO
GRAFICO_DETAIL = baseapp_+DETAIL_+GRAFICO



#imagem
IMAGEM = 'imagem'
IMAGEM_DELETE = baseapp_+DELETE_+IMAGEM
IMAGEM_CREATE = baseapp_+CREATE_+IMAGEM
IMAGEM_UPDATE = baseapp_+UPDATE_+IMAGEM
IMAGEM_LIST = baseapp_+LIST_+IMAGEM
IMAGEM_DETAIL = baseapp_+DETAIL_+IMAGEM



ADD_PRODUTO = 'store_add_produto'
ADD_CHAMADO = 'store_add_chamado'
DETAIL_CHAMADO = 'store_detail_chamado'
DELETE_DASHBOARD=''